//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class DebugCameraCaptureElement:DebugInterface.IDebugElement
{
	public GstBaseTexture SrcTexture;
	public DebugCameraCaptureElement (GstBaseTexture src)
	{
		SrcTexture = src;
	}

	public string GetDebugString()
	{
		string str = "";
		if (SrcTexture != null) {
			for(int i=0;i<SrcTexture.GetTextureCount();++i)
			{
				str+="Camera Source["+i.ToString()+"]= "+SrcTexture.GetCaptureRate(i);
				str+="\n";
			}
			return str;
		}
		return "No Camera Source Found! ";
	}
}
